/**
 * Mock User Accounts
 */
export const mockUserList = [
  {
    userId: "1",
    firstName: "Logan ",
    lastName: "Barnett",
    password: "acmegames",
    email: "logan.barnett@example.com",
    dateOfBirth: "16/08/1975",
  },
  {
    userId: "2",
    firstName: "Kenzi ",
    lastName: "Mccoy",
    password: "acmegames",
    email: "kenzi.mccoy@example.com",
    dateOfBirth: "02/12/1980",
  },
  {
    userId: "3",
    firstName: "Edna",
    lastName: "Frazier",
    password: "acmegames",
    email: "edna.frazier@example.com",
    dateOfBirth: "26/04/1990",
  },
  {
    userId: "4",
    firstName: "Nevaeh",
    lastName: "Kennedy",
    password: "acmegames",
    email: "nevaeh.kennedy@example.com",
    dateOfBirth: "09/01/2001",
  },
  {
    userId: "5",
    firstName: "Diana",
    lastName: "Holmes",
    password: "acmegames",
    email: "diana.holmes@example.com",
    dateOfBirth: "06/08/2010",
  },
  {
    userId: "6",
    firstName: "Dianne",
    lastName: "Coleman",
    password: "acmegames",
    email: "dianne.coleman@example.com",
    dateOfBirth: "16/11/2000",
  },
  {
    userId: "7",
    firstName: "Dora",
    lastName: "Griffin",
    password: "acmegames",
    email: "dora.griffin@example.com",
    dateOfBirth: "13/03/2011",
  },
  {
    userId: "8",
    firstName: "Jessica",
    lastName: "Murray",
    password: "acmegames",
    email: "jessica.murray@example.com",
    dateOfBirth: "06/08/1991",
  },
  {
    userId: "9",
    firstName: "Zack",
    lastName: "Lambert",
    password: "acmegames",
    email: "zack.lambert@example.com",
    dateOfBirth: "08/08/1980",
  },
  {
    userId: "10",
    firstName: "Mitsuya4",
    lastName: "April",
    password: "Soto",
    email: "april.soto@example.com",
    dateOfBirth: "26/08/1972",
  },
  {
    userId: "11",
    firstName: "Mitsuya1",
    lastName: "Watanabe1",
    password: "acmegames",
    email: "",
    dateOfBirth: "06/10/1975",
  },
  {
    userId: "12",
    firstName: "Maxine",
    lastName: "Baker",
    password: "acmegames",
    email: "maxine.baker@example.com",
    dateOfBirth: "06/08/2020",
  },
  {
    userId: "13",
    firstName: "vincent",
    lastName: "harvey",
    password: "acmegames",
    email: "vincent.harvey@example.com",
    dateOfBirth: "06/08/2020",
  },
  {
    userId: "14",
    firstName: "Derrick",
    lastName: "Steeves",
    password: "acmegames",
    email: "derrick.steeves@example.com",
    dateOfBirth: "06/08/2020",
  },
];
